// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function() {
    var c, rds, x, y;
    x = 0;
    y = 0;
    rds = 0;
    while (true) {
      x = Math.random() * 2 - 1;
      y = Math.random() * 2 - 1;
      rds = x * x + y * y;
      if (!(rds === 0 || rds > 1)) {
        break;
      }
    }
    c = Math.sqrt(-2 * Math.log(rds) / rds);
    return [x * c, y * c];
  };

}).call(this);
