// Generated by CoffeeScript 1.3.3
(function() {
  var Market, NSE, Stock, humanize, inspect, log, _ref;

  inspect = require('util').inspect;

  log = console.log;

  _ref = require('./market'), Market = _ref.Market, Stock = _ref.Stock, humanize = _ref.humanize;

  NSE = new Market({
    name: "Node Stock Exchange",
    symbol: "NSE",
    products: {
      JS: new Stock({
        name: "JavaScript",
        code: "JS",
        volume: 30000,
        price: 31.30
      }),
      RB: new Stock({
        name: "Ruby",
        code: "JS",
        volume: 30000,
        price: 31.30
      }),
      PY: new Stock({
        name: "Python",
        code: "PY",
        volume: 30000,
        price: 30.00
      })
    }
  });

  NSE.createAccount("john", "JohnDoe", 5000);

  NSE.open();

  require('zappa')(function() {
    this.enable('serve jquery');
    this.get({
      '/': function() {
        return this.render({
          index: {
            layout: false,
            title: 'NSE'
          }
        });
      }
    });
    this.get({
      '/admin/market/open': function() {
        return NSE.open();
      }
    });
    this.get({
      '/admin/market/close': function() {
        return NSE.close();
      }
    });
    this.on({
      login: function() {
        this.client.username = this.data.username;
        return this.client.session = NSE.login(this.data.username, this.data.password);
      }
    });
    this.on({
      buy: function() {
        var _this = this;
        return this.client.session.buy(this.client.code, this.client.volume, function() {
          _this.broadcast({
            bought: {
              username: _this.client.username,
              symbol: _this.data.symbol,
              volume: _this.data.volume
            }
          });
          return _this.emit({
            bought: {
              username: _this.client.username,
              symbol: _this.data.symbol,
              volume: _this.data.volume
            }
          });
        });
      }
    });
    this.on({
      sell: function() {
        var _this = this;
        return this.client.session.sell(this.client.code, this.client.volume, function() {
          _this.broadcast({
            sold: {
              username: _this.client.username,
              symbol: _this.data.symbol,
              volume: _this.data.volume
            }
          });
          return _this.emit({
            sold: {
              username: _this.client.username,
              symbol: _this.data.symbol,
              volume: _this.data.volume
            }
          });
        });
      }
    });
    this.client({
      '/index.js': function() {
        var _this = this;
        this.connect();
        this.on({
          bought: function() {
            return $('#panel').append("<p>" + this.data.username + " bought " + this.data.volume + " " + (humanize(this.data.symbol)) + "</p>");
          }
        });
        this.on({
          sold: function() {
            return $('#panel').append("<p>" + this.data.username + " sold " + this.data.volume + " " + (humanize(this.data.symbol)) + "</p>");
          }
        });
        return $(function() {
          _this.emit({
            'login': {
              username: prompt('Username'),
              password: prmpt('Password')
            }
          });
          $('#order').focus();
          return $('button').click(function(e) {
            _this.emit({
              buy: {
                text: $('#order').val()
              }
            });
            $('#order').val('').focus();
            return e.preventDefault();
          });
        });
      }
    });
    return this.view({
      index: function() {
        doctype(5);
        return html(function() {
          head(function() {
            title('Node Stock Exchange');
            script({
              src: '/socket.io/socket.io.js'
            });
            script({
              src: '/zappa/jquery.js'
            });
            script({
              src: '/zappa/zappa.js'
            });
            return script({
              src: '/index.js'
            });
          });
          return body(function() {
            div({
              id: 'panel'
            });
            return form(function() {
              input({
                id: 'symbol'
              });
              input({
                id: 'volume'
              });
              button('Buy');
              return button('Sell');
            });
          });
        });
      }
    });
  });

}).call(this);
